### PR TITLE
Relative (mswin) path fix + minor refactoring

### PR DESCRIPTION
**Pull request by ennovum**

### CODE REVIEW

**Comment by gronke** [comment]
LGTM :+1: 

@ennovum would you mind rebasing so that this changes can be merged?

**Comment by ennovum** [comment]
@gronke I tried, but it's no use- the codebase changed too much. Some of my adjustments are already applied. Sorry about that.

**Comment by gronke** [comment]
Thanks anyway! Re-applied your refactoring to the current master and added one test for backslashes in file exclusions.

@ennovum :beers:

**Comment by ennovum** [comment]
@gronke Thanks! I'm glad I could help a bit. :beers:

**Pull request closed without merging**
